### ISSUE TITLE
[Bug Report] First google search result for transformer lens is a 404

### ISSUE THREAD

**Issue by FabienRoger** [TransformerLensOrg/TransformerLens#593]
The first google search result for "transformer lens" is https://neelnanda-io.github.io/TransformerLens/ which has been taken down. It should ideally redirect to the correct documentation.

![image](https://github.com/TransformerLensOrg/TransformerLens/assets/15524303/6fc2e845-c9ca-430f-b262-35362c0f0cf1)

### Checklist

- [ x ] I have checked that there is no similar [issue](https://github.com/TransformerLensOrg/TransformerLens/issues) in the repo

**Comment by jbloomAus** [comment]
It got moved to TransforerLensOrg recently. Probably google will reindex automatically at some point?

**Comment by ArthurConmy** [comment]
This has moved to https://transformerlensorg.github.io/TransformerLens/

**Comment by bryce13950** [comment]
This is something that we do not have any control on. Github does not give you the option to configure those sorts of things. You can configure individual page redirects, but you cannot redirect entire sites. It will eventually be removed from Google results as Google does it's thing with indexing, and the main repo has already been promoted to the number result since this was opened.
