### ISSUE TITLE
[Proposal] Usage with openai/transformer-debugger

### ISSUE THREAD

**Issue by fzyzcjy** [TransformerLensOrg/TransformerLens#738]
### Proposal 

Hi thanks for the library! I also see https://github.com/openai/transformer-debugger, which has some interesting GUI tools, thus looks like complementary to TransformerLens. Since that lib only supports GPT2, I wonder whether TransformerLens can use its strong hook mechanism and existing support to a large amount of modern architectures to enhance that library. Then we can have a GUI for many architectures :)

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/TransformerLensOrg/Transformerlens/issues) in the repo (**required**)

**Comment by neelnanda-io** [comment]
This seems more like something someone should add to the transformer
debugger repo than to TransformerLens. Cool idea though, and I'd love to
see you or someone else do this

**Comment by fzyzcjy** [comment]
That looks pretty reasonable!

**Comment by bryce13950** [comment]
@fzyzcjy if you are interested in doing this, let me know. I am not very familiar with the transformer-debugger code base, but I am sure I can point you in the right direction on how to integrate the two together. I am going to close this, since it is irrelevant to the code base of TransformerLens, but I would be happy to sit down and go through the code to map out how you would go about doing this.

**Comment by fzyzcjy** [comment]
Thank you! Currently I am happy with TransformerLens, but if in the future I need to use transformer-debugger I will discuss more.
